import { ElementRef } from '@angular/core';
import { NgControl } from '@angular/forms';
import { Subject } from 'rxjs';
export declare const BIG_STEP = 10;
export declare const SMALL_STEP = 1;
export declare function normalizeSplitter(value: string): string;
export declare function isFloat(value: string): boolean;
export declare function isInt(value: string): boolean;
export declare function isDigit(value: string): boolean;
export declare function getPrecision(value: number): number;
export declare function add(value1: number, value2: number): number;
export declare class McNumberInput {
    private elementRef;
    private ngControl;
    bigStep: number;
    step: number;
    min: number;
    max: number;
    value: any;
    focused: boolean;
    readonly stateChanges: Subject<void>;
    get nativeElement(): HTMLInputElement;
    constructor(elementRef: ElementRef, ngControl: NgControl, step: string, bigStep: string, min: string, max: string);
    focusChanged(isFocused: boolean): void;
    onKeyDown(event: KeyboardEvent): void;
    onPaste(event: any): void;
    stepUp(step: number): void;
    stepDown(step: number): void;
    private viewToModelUpdate;
}
